-- Gugugaga Client cloud configs: shared client configurations.
-- Run this once in the Supabase SQL editor of your project.
--
-- Abuse model (why this cannot be crashed or filled up):
--   * Only the public anon key is used; RLS allows SELECT and INSERT only.
--     UPDATE and DELETE are impossible through the API.
--   * Every row is capped at 32 KB of JSON and must be a single JSON object.
--     Files/archives are never accepted, so zip bombs do not apply.
--     (PostgreSQL's jsonb parser itself also rejects pathological nesting depths.)
--   * Upload throttle: at most 5 uploads per author name per minute, enforced
--     directly in the INSERT policy.
--   * Retention trigger: after every upload the table is pruned back to the
--     newest 500 rows. The table can therefore never grow beyond
--     ~500 * 32 KB ≈ 16 MB, comfortably inside the Supabase FREE tier
--     (500 MB database, 5 GB egress/month, no credit card required).
--   * The client additionally caps every response at 512 KB and every displayed
--     string at 48 characters, so a hostile row cannot flood the game either.

create table if not exists public.aerialmace_configs (
    id          bigint generated by default as identity primary key,
    name        text        not null check (char_length(name) between 1 and 48),
    author      text        not null default '' check (char_length(author) <= 48),
    config      jsonb       not null,
    created_at  timestamptz not null default now()
);

-- Row level security: everyone may read shared configs and everyone may upload one.
-- Nothing may be updated or deleted through the public anon key.
alter table public.aerialmace_configs enable row level security;

drop policy if exists "public read configs" on public.aerialmace_configs;
create policy "public read configs"
    on public.aerialmace_configs
    for select
    to anon
    using (true);

drop policy if exists "public upload configs" on public.aerialmace_configs;
create policy "public upload configs"
    on public.aerialmace_configs
    for insert
    to anon
    with check (
        jsonb_typeof(config) = 'object'
        and octet_length(config::text) <= 32768
        -- Upload throttle: max 5 uploads per author name per minute.
        and (
            select count(*)
            from public.aerialmace_configs older
            where older.author = author
              and older.created_at > now() - interval '1 minute'
        ) < 5
    );

-- Keep lookups fast (list ordering and the throttle subquery).
create index if not exists aerialmace_configs_created_at_idx
    on public.aerialmace_configs (created_at desc);
create index if not exists aerialmace_configs_author_created_at_idx
    on public.aerialmace_configs (author, created_at desc);

-- Retention: keep only the newest 500 rows. SECURITY DEFINER is required because
-- the anon role has no DELETE right (by design); the function runs with table
-- owner rights and is only reachable through this INSERT trigger.
create or replace function public.prune_aerialmace_configs()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.aerialmace_configs
    where id in (
        select id
        from public.aerialmace_configs
        order by id desc
        offset 500
    );
    return null;
end;
$$;

drop trigger if exists prune_aerialmace_configs_trigger on public.aerialmace_configs;
create trigger prune_aerialmace_configs_trigger
    after insert on public.aerialmace_configs
    for each statement
    execute function public.prune_aerialmace_configs();
