-- AerialMace cloud configs: shared client configurations.
-- Run this once in the Supabase SQL editor of your project.

create table if not exists public.aerialmace_configs (
    id          bigint generated by default as identity primary key,
    name        text        not null check (char_length(name) between 1 and 48),
    author      text        not null default '' check (char_length(author) <= 48),
    config      jsonb       not null,
    created_at  timestamptz not null default now()
);

-- Row level security: everyone may read shared configs and everyone may upload one.
-- Nothing may be updated or deleted through the public anon key.
alter table public.aerialmace_configs enable row level security;

drop policy if exists "public read configs" on public.aerialmace_configs;
create policy "public read configs"
    on public.aerialmace_configs
    for select
    to anon
    using (true);

drop policy if exists "public upload configs" on public.aerialmace_configs;
create policy "public upload configs"
    on public.aerialmace_configs
    for insert
    to anon
    with check (jsonb_typeof(config) = 'object' and octet_length(config::text) <= 32768);

-- Optional: keep the table small by only indexing what the client lists.
create index if not exists aerialmace_configs_created_at_idx
    on public.aerialmace_configs (created_at desc);
